services:
  postgres:
    container_name: nomina_postgres
    image: postgres:16-alpine 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nomina_db
      PGDATA: /var/lib/postgresql/data 
    volumes:
      - ./.docker/pg:/var/lib/postgresql/data
    networks:
      - nomina_net

  redis:
    container_name: nomina_redis
    image: redis:alpine
    command: redis-server --appendonly yes # Ativa persistÃªncia de dados (AOF)
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/data
    networks:
      - nomina_net

networks:
  nomina_net:
    driver: bridge